services:
  sbc:
    build:
      context: .
      target: sbc
    restart: unless-stopped
    container_name: recorder
    network_mode: host
    privileged: true
    env_file:
      - .env
    volumes:
      - ./workspace:/home/pilot/workspace
      - /dev:/dev
      - /mnt/ssd:/mnt/ssd
    stdin_open: true
    tty: true
    command: bash -c "source /opt/ros/jazzy/setup.bash && python3 app.py"